### ISSUE TITLE
bad link in example file

### ISSUE THREAD

**Issue by SBFRF** [NOAA-ORR-ERD/gridded#49]
Hey all,
New to the gridded package, so i was trying to use the examples, specifically UGRID_plotting_COMT.py and ran into an error when trying to pull down the data specifically line 74. i checked out the SELFE link and it seems like there isn't a server at https://comt.sura.org/thredds 

Help would be much appreciated!

**Comment by SBFRF** [comment]
on further investigation, the link in the untitled.py and trajectory.py examples doesn't exist. `http://geoport.whoi.edu/thredds/dodsC/examples/bora_feb.nc`
there is no examples folder on that server (at least publicly accessible)

**Comment by rsignell-usgs** [comment]
That catalog got left out of a recent upgrade to our thredds server.   It should be working now. 

Thanks @SBFRF for letting us know!  You probably just saved a bunch of others from frustration also!

**Comment by SBFRF** [comment]
thanks @rsignell-usgs

**Comment by ChrisBarker-NOAA** [comment]
Thanks both!
@SBFRF: if you confirm that i's working, let us know, so we can clasoe the issue.

And please do report any other issues with the examples, they have not recieved any attnetion for a long while.

-CHB

**Comment by SBFRF** [comment]
@ChrisBarker-NOAA the `http://geoport.whoi.edu/thredds/dodsC/examples/bora_feb.nc` works.  The COMT url `https://comt.sura.org/thredds` for which i first opened the issue, still does not work.   This link is in the `examples/UGRID_plotting_COMT.py` file.  I assume the server was moved.  

Regarding other issues with the examples, would you like me to open separate issues or rename this one to update examples?  The `load_arbitrary_ugrid.py` example doesn't seem to work out of the box.

**Comment by ChrisBarker-NOAA** [comment]
Thanks!

Separate issues would be great, if it's not too much trouble.

I'm not too surprised that load_arbitrary_ugrid.py isn't working, the loading code has been refactored (and needs more) -- so yes, and issue on that one would be great.
